import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/providers/QueryProvider";

// APP METADATA
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ROOT LAYOUT
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* GLOBAL PROVIDERS */}
      <body>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
